### ISSUE TITLE
Unable to relink in BeamLink since metadata messages fixed

### ISSUE THREAD

**Issue by valsnoisytoys** [Tromino/BeamLink-1.0#1]
Since the latest Beam change that caused Beamlink to keep sending 'metadata' comments instead of the actual comment, I unlinked my chats until it was updated and the Beam messages started working again.  As of 2(?) days ago I noticed the 'metadata' messages were gone, so I attempted to relink my chats but I've had no luck.  Beamlink is not joining either my Beam or my Twitch channels.

Is Beamlink still being worked on?  I'm unable to find any updates here, on Beam, on Twitter, or by searching the internet in general.

Thank you!

**Comment by Tromino** [comment]
BenBot and its IRC server has been weird for me for a few times. I think SHA_256 is making it so it connect to Beam directly, instead of through BenBot. For now I could try restarting it, and see if that helps any. It will take a few minutes.

**Comment by Tromino** [comment]
The messagemeta thing still doesn't look fixed to me... weird.

**Comment by valsnoisytoys** [comment]
Actually yeah, I just went there again myself and saw them, came back to comment to that effect but  you beat me too it.  Basically it looks like the comments from Twitch are coming into Beam, but Beam comments are going back as metadata comments. I'll try again in a few minutes to see if the linking is working again. 

Thanks for the quick reply!

**Comment by Tromino** [comment]
The problem is that BenBot's IRC server (which BeamLink currently uses to connect to Beam) is actually *giving* me the "messagemeta" messages, instead of the actual messages. Even commands like "!link" get returned to BeamLink as "messagemeta". Either Ben needs to fix BenBot's Beam IRC server, or I just stop using it and connect to Beam directly.

**Comment by valsnoisytoys** [comment]
Oh! I see. Thanks for explaining. Hm. I guess I'll check back and see what route you take to fix it?

**Comment by valsnoisytoys** [comment]
Well the join issue has been fixed for a while, but as of late beamlink is not staying in chat. Another issue I assume?  I'll mark this one closed, as well, I can join, I just can't stay joined. :P

**Comment by Tromino** [comment]
Yeah, BenIRC broke again I think. Me and @lite20 are making an update that will connect to Beam directly.
