### ISSUE TITLE
BeamLink doesn't correctly ignore its own Beam messages

### ISSUE THREAD

**Issue by Tromino** [Tromino/BeamLink-1.0#3]
Testing with the BeamLinkDev account on both Twitch and Beam. #2
![](http://i.imgur.com/eMWoeVD.png)

**Comment by lite20** [comment]
This same issue occurs on Twitch too.

**Comment by lite20** [comment]
Did you remember to configure accounts.json? :P https://github.com/Tromino/BeamLink-1.0/blob/master/accounts.json

**Comment by ProbablePrime** [comment]
I apologise, I must of made a mess. 

I'll fix this for you tonight.

**Comment by Tromino** [comment]
It also seems like it's getting messages from Beam twice, though it doesn't look like it's what's causing the Twitch reposts and doesn't seem to affect anything. ![](http://i.imgur.com/6ObJWWZ.png)

**Comment by ProbablePrime** [comment]
![](http://i.ahref.co.uk/u/r/VUHW.png)

I'm not seeing the same thing. In the chats, I am seeing the same problem in the console though I'll take a look

**Comment by ProbablePrime** [comment]
On second thoughts, No. I'm not seeing any problems.

![](http://i.ahref.co.uk/u/r/C8ph.png)

Perhaps its something to do with your channels.json?

**Comment by Tromino** [comment]
Try unlinking and relinking. It might only be for newly-linked channels.

**Comment by ProbablePrime** [comment]
Found the problem. Working on it!

**Comment by ProbablePrime** [comment]
#4 contains the fix.

![](http://i.ahref.co.uk/u/r/wzEF.png)

Ignore the white extranous message I removed it before commiting
